# Generated by Django 3.0.3 on 2020-03-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='shortened_url',
            new_name='shortcode',
        ),
    ]
