# Generated by Django 3.0.3 on 2020-03-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200331_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='full_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
